### PR TITLE
Cosine similarity model

### PR DESCRIPTION
**Pull request by Aparajithashri**

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
@tamilarasumk731 @smartsri18 Please try this in your local, we can have a call late tonight.

**Comment by tamilarasumk731** [comment]
Yeah Sure @AkbarHabeeb

**Comment by Aparajithashri** [comment]
Anna I have update the cosine similarity model and this recommends based on plot of the given movie. Genre based model use cosine similarity but this recommends based on genre. And another model, popularity based model recommends the movie based on number of ratings and rating points.

**Comment by AkbarHabeeb** [comment]
Good one @Aparajithashri .
@smartsri18 can you please review this work and analyse the process for transforming it to an API.

**Comment by AkbarHabeeb** [comment]
@Aparajithashri Code has been converted into a web service. Closing this reference PR.

**Comment by Aparajithashri** [comment]
Hi anna,
I saw that na, thats awesome 🤩.

**Pull request closed without merging**
