### PR TITLE
Aparajithashri/m lmodel

### PR DESCRIPTION
**Pull request by Aparajithashri**

### CODE REVIEW

**Comment by Aparajithashri** [comment]
@tamilarasumk731  I have updated the code.Check this anna.

**Comment by tamilarasumk731** [comment]
@Aparajithashri Seems to be some conflicts in the app.py
Can you resolve it by pull the lastest code from dev branch?

**Comment by AkbarHabeeb** [comment]
@tamilarasumk731 Please make the code sync to master on a weekly basis. And I feel, I need to have a full walkthrough of this repo anytime before June 20. I hardly get the details in it.

**Comment by tamilarasumk731** [comment]
@AkbarHabeeb Sure, we can make it.

**Pull request merged**
